# Generated by Django 5.1.1 on 2024-09-30 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSleuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leakdetectionlog',
            name='status',
            field=models.CharField(default='unresolved', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('.txt', 'Text File'), ('.pdf', 'PDF File'), ('.jpg', 'JPEG Image'), ('.bmp', 'Bitmap Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='file',
            name='version_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
