# Generated by Django 5.1.1 on 2024-10-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataSleuthApp', '0003_alter_agent_name_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
